a=input('nhap so thu nhat:')
max = int(a)
a=input('nhap so thu hai:')
if (int(a)>=int(max)): max =int(a)
a=input('nhap so thu ba:')
if (int(a)>=int(max)): max=int(a)
a=input('nhap so thu tu:')
if (int(a)>=int(max)): max=int(a)
print('so lon nhat la:',max)