thu=input('Nhap thu can dich 2<>8:')
if (int(thu)==2):print('-->Monday')
if (int(thu)==3):print('-->Tuesday')
if (int(thu)==4):print('-->Wednesday')
if (int(thu)==5):print('-->Thursday')
if (int(thu)==6):print('-->Friday')
if (int(thu)==7):print('-->Saturday')
if (int(thu)==8):print('-->Sunday')
if (int(thu)<=1) or (int(thu)>=9): print('Khong co thu nay ')
    