a = input('nhap so thu nhat:')
s = int(a)
a = input('nhap so thu hai:')
s = s+int(a)
a = input('nhap so thu ba:')
s = s+int(a)
a = input('nhap so thu tu:')
s = s+int(a)
print('trung binh cong:', s/4)