a = int(input("nhap vao he so a = "))
b = int(input("nhap vao he so b ="))
print("a+b=", (a+b))
print("a-b=", (a-b))
print("a*b=", (a*b))
print("a/b=", (a/b))
print("a+b=", (a % b))
print("a+b=", (a**b))
print(a == b)
print(a != b)
